# Generated by Django 5.1.1 on 2024-09-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_products', to='products.category', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
